services:
  recipe-book:
    container_name: recipe-book
    hostname: recipe-book
    build: .
    ports:
      - "3000:80"
  
  # recipe-book:
  #   container_name: recipe-book
  #   hostname: recipe-book
  #   image: nginx:alpine
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./out/:/usr/share/nginx/html

networks:
  default:
    name: local_nw
    external: true