name = "recipe-book"
compatibility_date = "2024-10-01"

# Cloudflare Pages configuration
pages_build_output_dir = "out"

# Build configuration
[build]
command = "npm run build"
cwd = "/"

# Environment variables for build
[vars]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"